name: telephonist
description: A sample command-line application
dependencies:
  bootstrap: "3.3.4"
  browser: any
  redis_client: any
  stomp: any
  args: any
  logging: 0.11.3
#transformers:
#- bootstrap:
#    url: //maxcdn.bootstrapcdn.com/bootstrap/3.3.4
#    version: 3.3.4